on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          python-version: 3.7
      - name: Install packages
      - run: pip install -r requirements.txt
      - name: Run Local TFX
        run: make run-local