on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install python packages
        run: pip install -r requirements.txt
      - name: Install skaffold
        run: make install-skaffold
      - name: Update tfx pipeline
        run: make tfx-update-pipeline